import type { Metadata } from 'next'
import localFont from 'next/font/local'
import '../globals.css'
import { ThemeProvider } from '@/components/providers/ThemeProvider'
import { getLocale, getMessages } from 'next-intl/server'
import { NextIntlClientProvider } from 'next-intl'

const emberBd = localFont({
   src: '../fonts/Ember_Bd.ttf',
   variable: '--font-ember-bd',
   weight: '100 900'
})

const emberHe = localFont({
   src: '../fonts/Ember_He.ttf',
   variable: '--font-ember-he',
   weight: '100 900'
})

const emberLt = localFont({
   src: '../fonts/Ember_Lt.ttf',
   variable: '--font-ember-lt',
   weight: '100 900'
})

const emberRg = localFont({
   src: '../fonts/Ember_Rg.ttf',
   variable: '--font-ember-rg',
   weight: '100 900'
})

const emberTh = localFont({
   src: '../fonts/Ember_Th.ttf',
   variable: '--font-ember-th',
   weight: '100 900'
})

const emberMedium = localFont({
   src: '../fonts/Ember-Medium.ttf',
   variable: '--font-ember-medium',
   weight: '100 900'
})

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app'
}

export default async function RootLayout({
   children
}: Readonly<{
   children: React.ReactNode
}>) {
   const locale = await getLocale()
   const messages = await getMessages()

   return (
      <html lang={locale} suppressHydrationWarning>
         <body
            className={`${emberBd.variable} ${emberHe.variable} ${emberLt.variable} ${emberRg.variable} ${emberTh.variable} ${emberMedium.variable} antialiased font-regular`}
         >
            <ThemeProvider
               attribute="class"
               defaultTheme="system"
               enableSystem
               disableTransitionOnChange
            >
               <NextIntlClientProvider messages={messages}>
                  {children}
               </NextIntlClientProvider>
            </ThemeProvider>
         </body>
      </html>
   )
}
