import { Metadata } from 'next'
import localFont from 'next/font/local'
import Image from 'next/image'
import React, { Suspense } from 'react'
import '../globals.css'
import Footer from './_components/Footer'
import NextIntlProvider from '@/components/providers/NextIntlProvider'
import ProtectedRoute from '@/components/providers/ProtectedRoute'
import ReduxProvider from '@/components/providers/ReduxProvider'

const emberBd = localFont({
   src: '../fonts/Ember_Bd.ttf',
   variable: '--font-ember-bd',
   weight: '100 900'
})

const emberHe = localFont({
   src: '../fonts/Ember_He.ttf',
   variable: '--font-ember-he',
   weight: '100 900'
})

const emberLt = localFont({
   src: '../fonts/Ember_Lt.ttf',
   variable: '--font-ember-lt',
   weight: '100 900'
})

const emberRg = localFont({
   src: '../fonts/Ember_Rg.ttf',
   variable: '--font-ember-rg',
   weight: '100 900'
})

const emberTh = localFont({
   src: '../fonts/Ember_Th.ttf',
   variable: '--font-ember-th',
   weight: '100 900'
})

const emberMedium = localFont({
   src: '../fonts/Ember-Medium.ttf',
   variable: '--font-ember-medium',
   weight: '100 900'
})

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app'
}

export default function AuthLayout({
   children
}: Readonly<{ children: React.ReactNode }>) {
   return (
      <html lang="en" suppressHydrationWarning>
         <body
            className={`${emberBd.variable} ${emberHe.variable} ${emberLt.variable} ${emberRg.variable} ${emberTh.variable} ${emberMedium.variable} antialiased font-regular`}
         >
            <ReduxProvider>
               <ProtectedRoute>
                  <Suspense fallback={null}>
                     <NextIntlProvider>
                        <div className="bg-auth fixed z-[-1] h-screen w-screen"></div>
                        <div className="flex h-full w-full flex-col text-primary-black">
                           <div className="mx-auto w-full py-5">
                              <div className="pb-8 pt-5">
                                 <Image
                                    src="/images/aws-logo.png"
                                    alt="logo"
                                    width={84}
                                    height={51}
                                    className="mx-auto"
                                 />
                              </div>
                           </div>
                           <main className="container mx-auto max-h-screen pb-12">
                              {children}
                           </main>
                           <Footer />
                        </div>
                     </NextIntlProvider>
                  </Suspense>
               </ProtectedRoute>
            </ReduxProvider>
         </body>
      </html>
   )
}
